class AddGalleries1 < ActiveRecord::Migration
  def change
		Gallery.create!(title: "Wedgewood Upland Hills Bridal Show",		event_date: Date.new(2014,11,5),	album_url: "http://snapshowmagic.smugmug.com/Events/Wedgewood-Upland-Hills")
		Gallery.create!(title: "Wedgewood at The Retreat Bridal Show",	event_date: Date.new(2014,10,29),	album_url: "http://snapshowmagic.smugmug.com/Events/Wedgewood-at-The-Retreat/")
		Gallery.create!(title: "Wedgewood at Indian Hills Bridal Show",	event_date: Date.new(2014,10,22),	album_url: "http://snapshowmagic.smugmug.com/Events/Wedgewood-at-Indian-Hills/")
		Gallery.create!(title: "Wedgewood at Glen Ivy Bridal Show",			event_date: Date.new(2014,10,14),	album_url: "http://snapshowmagic.smugmug.com/Events/Wedgewood-at-Glen-Ivy-Bridal")
		Gallery.create!(title: "Matthew and Holly",											event_date: Date.new(2014,10,11),	album_url: "http://snapshowmagic.smugmug.com/Weddings/Matthew-and-Holly-10112014")
		Gallery.create!(title: "Oscar and Roxana",											event_date: Date.new(2014,10,4),	album_url: "http://snapshowmagic.smugmug.com/Weddings/Oscar-and-Roxana-100414")
		Gallery.create!(title: "Andrew and Carmen",											event_date: Date.new(2014,9,27),	album_url: "http://snapshowmagic.smugmug.com/Weddings/Andrew-and-Carmen-09272014")
		Gallery.create!(title: "NACE",																	event_date: Date.new(2014,8,20),	album_url: "http://snapshowmagic.smugmug.com/Events/NACE-20140820/")
		Gallery.create!(title: "Daniel and Laura",											event_date: Date.new(2014,8,15),	album_url: "http://snapshowmagic.smugmug.com/Weddings/Daniel-and-Laura-08152014")
		Gallery.create!(title: "The Queen Mary Bridal Show",						event_date: Date.new(2014,8,10),	album_url: "http://snapshowmagic.smugmug.com/Events/Bridal-Show-The-Queen-Mary")
		Gallery.create!(title: "William and Lauren",										event_date: Date.new(2014,7,26),	album_url: "http://snapshowmagic.smugmug.com/Weddings/William-and-Lauren-07262014")
		Gallery.create!(title: "Mike and Sara",													event_date: Date.new(2014,7,20),	album_url: "http://snapshowmagic.smugmug.com/Weddings/Mike-and-Sara-07202014/")
		Gallery.create!(title: "Jamie and Natalie",											event_date: Date.new(2014,6,27),	album_url: "http://snapshowmagic.smugmug.com/Weddings/Jamie-and-Natalie-06272014/n-T8gvj")
		Gallery.create!(title: "Scott and Ashleigh",										event_date: Date.new(2014,6,22),	album_url: "http://snapshowmagic.smugmug.com/Weddings/Scott-and-Ashleigh-062214")
		Gallery.create!(title: "Michael and Jennifer",									event_date: Date.new(2014,5,4),		album_url: "http://snapshowmagic.smugmug.com/Weddings/Michael-and-Jennifer-050414")
		Gallery.create!(title: "Wedgewood at The Retreat Bridal Show",	event_date: Date.new(2014,4,23),	album_url: "http://snapshowmagic.smugmug.com/Weddings/The-Retreat-Bridal-Show-042314")
		Gallery.create!(title: "Michael and Rachael",										event_date: Date.new(2014,4,11),	album_url: "http://snapshowmagic.smugmug.com/Weddings/Michael-and-Rachael-041114")
		Gallery.create!(title: "Wedgewood Vellano Bridal Show",					event_date: Date.new(2014,4,8),		album_url: "http://snapshowmagic.smugmug.com/Weddings/Vellano-Bridal-Show-040814")
		Gallery.create!(title: "Cory and Katrina",											event_date: Date.new(2014,4,4),		album_url: "http://snapshowmagic.smugmug.com/Weddings/Cory-and-Katrina-040414")
		Gallery.create!(title: "Daniel and Taylor",											event_date: Date.new(2014,3,21),	album_url: "http://snapshowmagic.smugmug.com/Weddings/Daniel-and-Taylor-032114")
		Gallery.create!(title: "Wedgewood at Indian Hills Bridal Show",	event_date: Date.new(2014,2,19),	album_url: "http://snapshowmagic.smugmug.com/Weddings/Indian-Hills-Bridal-Show-1-1")
		Gallery.create!(title: "Mark and Laisa",												event_date: Date.new(2014,2,9),		album_url: "http://snapshowmagic.smugmug.com/Weddings/Mark-and-Laisa-020914")
		Gallery.create!(title: "Paul and Michele",											event_date: Date.new(2014,2,1),		album_url: "http://snapshowmagic.smugmug.com/Weddings/Paul-and-Michele-020114")
		Gallery.create!(title: "Scott and Jenna",												event_date: Date.new(2013,12,15),	album_url: "http://snapshowmagic.smugmug.com/Weddings/Scott-and-Jenna-121513")
		Gallery.create!(title: "Wedgewood Upland Hills Bridal Show",		event_date: Date.new(2013,11,5),	album_url: "http://snapshowmagic.smugmug.com/Weddings/Upland-Hills-Bridal-Show")
		Gallery.create!(title: "Wedgewood at Glen Ivy Bridal Show",			event_date: Date.new(2013,10,29),	album_url: "http://snapshowmagic.smugmug.com/Weddings/Glen-Ivy-Bridal-Show-102931")
		Gallery.create!(title: "Wedgewood at The Retreat Bridal Show",	event_date: Date.new(2013,10,23),	album_url: "http://snapshowmagic.smugmug.com/Weddings/The-Retreat-Bridal-Show-102313")
		Gallery.create!(title: "Wedgewood at Indian Hills Bridal Show",	event_date: Date.new(2013,10,16),	album_url: "http://snapshowmagic.smugmug.com/Weddings/Indian-Hills-Bridal-Show-1")
		Gallery.create!(title: "Josh and Danielle",											event_date: Date.new(2013,10,11),	album_url: "http://snapshowmagic.smugmug.com/Weddings/Josh-and-Danielle-101113")
		Gallery.create!(title: "Wedgewood Vellano Bridal Show",					event_date: Date.new(2013,10,8),	album_url: "http://snapshowmagic.smugmug.com/Weddings/Vellano-Bridal-Show-100813")
		Gallery.create!(title: "Pete and Tawnee",												event_date: Date.new(2013,9,14),	album_url: "http://snapshowmagic.smugmug.com/Weddings/Pete-and-Tawnee-091413")
		Gallery.create!(title: "Joe and Janna",													event_date: Date.new(2013,9,6),		album_url: "http://snapshowmagic.smugmug.com/Weddings/Joe-and-Janna-090613")
		Gallery.create!(title: "Greg and Nicole",												event_date: Date.new(2013,7,21),	album_url: "http://snapshowmagic.smugmug.com/Weddings/Greg-and-Nicole-072113/30671446_HNfsMh")
		Gallery.create!(title: "Erik and Kelly",												event_date: Date.new(2013,7,19),	album_url: "http://snapshowmagic.smugmug.com/Weddings/Erik-and-Kelly-071913/30637055_ngM6Qc")
		Gallery.create!(title: "Josh and Theresa",											event_date: Date.new(2013,6,29),	album_url: "http://snapshowmagic.smugmug.com/Weddings/Josh-and-Teresa-062913/30267396_npNPrn")
		Gallery.create!(title: "Alex and Ashlee",												event_date: Date.new(2013,6,1),		album_url: "http://snapshowmagic.smugmug.com/Weddings/Alex-and-Ashlee-060113/29756578_ZhrgSL")
		Gallery.create!(title: "Luke and Misty",												event_date: Date.new(2013,5,26),	album_url: "http://snapshowmagic.smugmug.com/Weddings/Luke-and-Misty-052613/29644098_qbNkNN")
		Gallery.create!(title: "Daniel and Amber",											event_date: Date.new(2013,4,26),	album_url: "http://snapshowmagic.smugmug.com/Weddings/Daniel-and-Amber-042613/29120599_GMxggH")
		Gallery.create!(title: "Wedgewood at Glen Ivy Bridal Show",			event_date: Date.new(2013,4,18),	album_url: "http://snapshowmagic.smugmug.com/Weddings/Glen-Ivy-Bridal-Show-041813/28990308_pkFjNQ")
		Gallery.create!(title: "Daniel and Lauren",											event_date: Date.new(2013,3,30),	album_url: "http://snapshowmagic.smugmug.com/Weddings/Daniel-and-Lauren-033013/28684667_bnGdvD")
		Gallery.create!(title: "Wedgewood at The Retreat Bridal Show",	event_date: Date.new(2013,3,20),	album_url: "http://snapshowmagic.smugmug.com/Weddings/The-Retreat-Bridal-Show-032013/28534144_SdsgnZ")
		Gallery.create!(title: "Young and Vivian",											event_date: Date.new(2013,3,9),		album_url: "http://snapshowmagic.smugmug.com/Weddings/Young-and-Vivian-030913/28361784_pNcNCR")
		Gallery.create!(title: "Michael and Heather",										event_date: Date.new(2013,3,8),		album_url: "http://snapshowmagic.smugmug.com/Weddings/Michael-and-Heather-030813/28347204_XD9tv6")
		Gallery.create!(title: "Adrian and Adrianna",										event_date: Date.new(2013,2,23),	album_url: "http://snapshowmagic.smugmug.com/Weddings/Adrian-and-Adrianna-022313/28151176_QpWLwv")
		Gallery.create!(title: "Whispering Meadows Bridal Show",				event_date: Date.new(2013,2,2),		album_url: "http://snapshowmagic.smugmug.com/Weddings/Whispering-Meadows-Bridal-Show/27838013_pWvVKw")
		Gallery.create!(title: "Wedgewood at The Retreat Bridal Show",	event_date: Date.new(2012,11,15),	album_url: "http://snapshowmagic.smugmug.com/Weddings/The-Retreat-Bridal-Show-111512/26548041_7XM3Qr")
		Gallery.create!(title: "Wedgewood at Indian Hills Bridal Show",	event_date: Date.new(2012,10,24),	album_url: "http://snapshowmagic.smugmug.com/Weddings/Indian-Hills-Bridal-Show/26141664_fdZg4p")
		Gallery.create!(title: "Wedgewood at Glen Ivy Bridal Show",			event_date: Date.new(2012,10,17),	album_url: "http://snapshowmagic.smugmug.com/Weddings/Glen-Ivy-Bridal-Show-101712/25998255_DVSCLR")
		Gallery.create!(title: "Shad and Crystal",											event_date: Date.new(2012,8,25),	album_url: "http://snapshowmagic.smugmug.com/Weddings/Shad-and-Crystal-082512/24994050_JfpW4v")
		Gallery.create!(title: "Manuel and Victoria",										event_date: Date.new(2012,8,24),	album_url: "http://snapshowmagic.smugmug.com/Weddings/Manuel-and-Victoria-082412/24969841_2hJRwj")
		Gallery.create!(title: "Bogie and Kristen",											event_date: Date.new(2012,8,18),	album_url: "http://snapshowmagic.smugmug.com/Weddings/Bogie-and-Kristen-081812/24845669_M8dQ2w")
		Gallery.create!(title: "Darrall and Desiree",										event_date: Date.new(2012,8,12),	album_url: "http://snapshowmagic.smugmug.com/Weddings/Darrall-and-Desiree-081212/24727074_LTsC5Q")
		Gallery.create!(title: "Patrick and Andrea",										event_date: Date.new(2012,6,16),	album_url: "http://snapshowmagic.smugmug.com/Weddings/Patrick-and-Andrea-061612/23610292_jcSXPW")
		Gallery.create!(title: "Wedgewood at The Retreat Bridal Show",	event_date: Date.new(2012,4,18),	album_url: "http://snapshowmagic.smugmug.com/Weddings/The-Retreat-Bridal-Show-041712/22525525_Vtz77M")
		Gallery.create!(title: "Michael and Robin",											event_date: Date.new(2012,4,15),	album_url: "http://snapshowmagic.smugmug.com/Weddings/Michael-and-Robin-041512/22473732_3hBpgr")
		Gallery.create!(title: "Gabriel and Tiffanie",									event_date: Date.new(2012,4,14),	album_url: "http://snapshowmagic.smugmug.com/Weddings/Gabriel-and-Tiffanie-041412/22452942_vQqjc3")
		Gallery.create!(title: "Wedgewood at Glen Ivy Bridal Show",			event_date: Date.new(2012,2,23),	album_url: "http://snapshowmagic.smugmug.com/Weddings/Glen-Ivy-Bridal-Show-022312/21611219_4ZFPf3")
		Gallery.create!(title: "Andrew and Sara",												event_date: Date.new(2011,12,17),	album_url: "http://snapshowmagic.smugmug.com/Weddings/Andrew-and-Sara-121711/20646424_tfzVHm#1636967079_bFstZRw")
		Gallery.create!(title: "Kevin and Sarah",												event_date: Date.new(2011,11,13),	album_url: "http://snapshowmagic.smugmug.com/Weddings/Kevin-and-Sarah-111311/20075184_cNwfLf")
		Gallery.create!(title: "Mike and Natalie",											event_date: Date.new(2011,7,17),	album_url: "http://snapshowmagic.smugmug.com/Weddings/Mike-and-Natalie-71711/18102402_SCs5TF#1388823393_cPcGrvq")
		Gallery.create!(title: "Lowell and Panda",											event_date: Date.new(2010,11,27),	album_url: "http://snapshowmagic.smugmug.com/Weddings/Lowell-and-Panda-112710/14838209_ATGQ4#1106976954_AJFJn")
		Gallery.create!(title: "Ron and Susan",													event_date: Date.new(2010,10,10),	album_url: "http://snapshowmagic.smugmug.com/Weddings/Ron-and-Susan-101010/14640166_xHgqU#1089251791_Jdynm")
  end
end
